name: CI (Gradle / Spring Boot)

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint (Gradle check sin tests)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"
      - name: Setup Gradle (cache + wrapper validation)
        uses: gradle/actions/setup-gradle@v4
      - name: Permisos wrapper
        run: chmod +x gradlew
      - name: Ejecutar check (sin tests)
        run: ./gradlew check -x test --no-daemon
  build:
    name: Build (artefactos)
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"
      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4
      - name: Permisos wrapper
        run: chmod +x gradlew
      - name: Build (sin tests, ya corrieron)
        run: ./gradlew build -x test --no-daemon
      - name: Publicar JARs
        uses: actions/upload-artifact@v4
        with:
          name: app-jars
          path: build/libs/*.jar
