name: Goach CI with Gradle

on:
  push:
    branches: [ "develop" ]

jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'corretto'
          cache: gradle

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.1
        with:
          args: --baseline,qodana-baseline.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1618691014 }}

  build:
    runs-on: ubuntu-latest
  
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: "Pokemon.2012"
          ACCEPT_EULA: "Y"
  
    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'corretto'
          cache: gradle
  
      - name: Wait for SQL Server
        run: |
          for i in {1..20}; do
            nc -z localhost 1433 && break
            sleep 5
          done
  
      - name: Run Tests
        run: ./gradlew clean test
        env:
          SPRING_DATASOURCE_URL: jdbc:sqlserver://localhost:1433;databaseName=goach;encrypt=false;trustServerCertificate=true
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: "Pokemon.2012"
          SPRING_JPA_HIBERNATE_DDL_AUTO: create
          SPRING_SQL_INIT_MODE: never
